/*
 * TIMER0_configuration.h
 *
 *  Created on: Jan 18, 2022
 *      Author: Mohy
 */

#ifndef INCLUDE_MCAL_TIMER0_TIMER0_CONFIGURATION_H_
#define INCLUDE_MCAL_TIMER0_TIMER0_CONFIGURATION_H_

#define TIMER0_MODE 							TIMER0_CTC_MODE
#define NON_PWM_OC0_MODE						NON_PWM_OC0_DISCONNECTED
#define PWM_OC0_MODE							PWM_OC0_DISCONNECTED
#define TIMER0_PRESCALLER_CONF					TIMER0_PRESCALLER_8
#define OVF_INTERRUPT_MODE						TIMER0_INTERRUPT_DISABLE
#define COMPARE_MATCH_INTERRUPT_MODE			TIMER0_INTERRUPT_ENABLE

#define TIMER0_OUTPUT_COMPARE_VALUE				199

#endif /* INCLUDE_MCAL_TIMER0_TIMER0_CONFIGURATION_H_ */
